### ISSUE TITLE
Join & Signup Form [meta]

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#156]
Posting a single issue on all things related to form: button, page, copy ....to make sure nothing slips. Most of this should be filed elsewhere. We can confirm that and then close this if there are no big questions. 

 - [x] #155 "Join" button in header should link to /join.
 - [x] "Sign up" will be button label everywhere else (including landing pages). 
 - [x] I propose we keep "Join" as label in the header for a stronger CTA. I expect lots of dissenting opinion.
 - [x] /join page includes a sign-up form. We could relabel the path but I vote to leave it for now.
 - [x] /join page has just a simple sign-up form. It's sparse. That's totally okay for now. We could repeat the Get Involved homepage component below _if and only if_ it's trivial to implement. 
 - [x]  #188 Sign up form is simple. New copy: Header & body: 
   - Header: Stay Connected 
   - Body: Sign up to receive updates with opportunities and news from the movement for a healthy internet.  
   - Input field
   - legal checkbox
   - "Sign up" button
  - [x] #189 Add form back to homepage.
- [ ] #164 Landing pages should have a form. Let's worry about the stuff above first.  

cc @alanmoo @taisdesouzalessa @gvn @sabrinang @hannahkane 

Any questions? Let's link and assign tickets.

**Comment by xmatthewx** [comment]
Forms are coming along well. @gvn says we can add the form back to the homepage (thanks @gvn) instead of the static CTA.  Adding to the list above.

**Comment by gvn** [comment]
All landed except for #164
