### ISSUE TITLE
Set up network-api templates -> mezzanine template deployments

### ISSUE THREAD

**Issue by Pomax** [mozilla/network#238]
migrated from https://github.com/mozilla/network-api/issues/87

This will rely on:
- [x] converting pug to django templates, https://github.com/mozilla/network/issues/239
- [x] making template conversion part of the network-api build https://github.com/mozilla/network/issues/240
- [ ] sending the converted template(s) over to the mezzanine repository https://github.com/mozilla/network/issues/241
- [ ] have the mezzanine repo automatically put them in the right place so that auto-deploy works https://github.com/mozilla/network/issues/242

**Comment by hannahkane** [comment]
@pomax - I'm a bit unclear on the status of this ticket, along with #240, #241, and #242. Are they in progress? Are they expected to be completed this week?

**Comment by Pomax** [comment]
They are, and hopefully, respectively. The work is blocked a bit on the mezzanine work that @cadecairos is doing on the network-api side.

**Comment by gvn** [comment]
@Pomax We can close this now, right?

**Comment by cadecairos** [comment]
Yes this is done. see: https://github.com/mozilla/network-api/issues/115
