### ISSUE TITLE
Launch Checklist

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#50]
@gvn @hannahkane @cadecairos  – I'd like to craft a Launch checklist now-ish, so we can ensure essential issues are filed. Do we have a template for this already? Or reference from Science site?

If we don't have a template, can we add ideas below and create one?

**Comment by xmatthewx** [comment]
List could have 3 sections, items ordered carefully in each. 
 - Pre-flight
 - Launch
 - Post-launch (immediate things that answer: anything broken?)
 
Some examples:  
 - [ ] quality tests completed `pre`
 - [ ] staff calendars clear for contingencies `pre`
 - [ ] build to production `launch`
 - [ ] analytics live and operational `post`
 - [ ] join form receiving submissions `post`
 - [ ] DNS operating as expected `post`
 - [ ] pages, components, fonts, images loading as expected `post`

**Comment by hannahkane** [comment]
@xmatthewx - can you clarify what the comms around the launch are?

**Comment by xmatthewx** [comment]
Comms to the existing network will come from Lotta with support from Paul and Lainie I believe. Comms to others is something we can worry about much later.

**Comment by hannahkane** [comment]
OK, the only things I would add to this would be comms-related, but if want to keep this tech-specific, I don't have anything to add at this point.

**Comment by cadecairos** [comment]
(copied from [here](https://github.com/MozillaFoundation/mofo-devops/blob/master/docs/go-live.md)

Note: Not all of these will be relevant.

- [ ] Conduct an RRA
- [ ] Perform  a Security Review
  - [ ] Does user generated content get displayed in-browser safely?
  - [ ] Does user generated content get stored in any way - is it done safely?
  - [ ] Is PII handled according to Mozilla's Privacy Policy?
  - [ ] If password information is stored, is it done using best practices? (bcrypt/scrypt + salt)
  - [ ] Does the site implement recommended security headers for HTTP requests? (HSTS, XFO, CSP, XCTO, etc)
  - [ ] Do POST/PUT/DELETE requests implement some form of Cross Site Request Forgery protection?
  - [ ] Does it have dependencies with known security vulnerabilities? (nsp, OWASP dependency-check)
- [ ] Does the system/site have adequate automated testing?
- [ ] Is there a contributors.json file present in the source repository, does it provide contact information in the event of an emergency?
- [ ] If automatically deployed, who can trigger deploys? Should deployment permission be limited? (branch/merge protection)
- [ ] Data Storage
  - [ ] Automatic Backups
  - [ ] Not publicly accessible AND/OR Strong Access credentials
- [ ] [node] Is it using an up-to-date LTS version of node?  
- [ ] Logs & Monitoring
  - [ ] Does this app require uptime monitoring? (pingdom)
  - [ ] Does this app need to be hooked into logentries
  - [ ] Does this app require log analysis (for alerting devs of runtime errors)

**Comment by gvn** [comment]
- [ ] remove Style Guide link from primary nav

**Comment by xmatthewx** [comment]
tais mentioned 404 page. filed elsewhere to track.  would be good to add to a canonical list. 
 - [ ] 404 page setup and working

**Comment by hannahkane** [comment]
@gvn @alanmoo @mmmavis @cadecairos - could you please sync up about the items in Cade's comment above and file/estimate individual tickets for categories of work that still need to be done (e.g. security review, testing, storage, logs)?

Then we can close this ticket. The other items no longer feel useful to keep in a ticket.

Thanks!

**Comment by alanmoo** [comment]
Tickets are open for the 2 remaining items from Chris's list.
