### ISSUE TITLE
Redesign hero based on feedback

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#60]
A few related things grouped in this ticket. 

 - [ ] #330 is about getting something, anything in the hero 
 - [ ] #343 more neutral nav bar for user generated pages
 - [ ] #426 menu icon position

**Comment by xmatthewx** [comment]
@sabrinang - share our fallback default option for implementation.

**Comment by sabrinang** [comment]
Hero graphic of slashes here: https://drive.google.com/file/d/0B4Q8pzCpDS_eRmh2dDVDUDZ0Q1U/view for Lime (Hex# B6D806)

**Comment by sabrinang** [comment]
flattened .png here: https://drive.google.com/file/d/0B4Q8pzCpDS_eNTlWdnJucGJFdHM/view

**Comment by xmatthewx** [comment]
We discussed last week with @gvn that we will stick with current green implementation until redesign based on feedback is done. Removing from Milestone. Marking as blocked.

**Comment by hannahkane** [comment]
@xmatthewx - can we close this ticket, or move it to a post-launch milestone?

**Comment by sabrinang** [comment]
By considering a dark or light nav, we can streamline the transition and styling effect with the menu when opened and the menu/close icon can stay in the same spot (related to https://github.com/mozilla/network/issues/426). We can also consider how the navigation can shrink when you scroll down the page. A concern with the white is that it may look too similar to mozilla.org which may not be visually distinct enough when we do not have a name yet.
<img width="1172" alt="nav hero options" src="https://cloud.githubusercontent.com/assets/2492510/26368234/e70ce6c0-3fa5-11e7-8716-660c6a298aab.png">

For user generated pages, it may be more versatile to use a neutral colour that can match any hero banner colour. In this example we can go with a dark nav instead of a colour themed nav (related to https://github.com/mozilla/network/issues/343):
<img width="1601" alt="Dark Nav" src="https://cloud.githubusercontent.com/assets/2492510/26367754/7bc454c6-3fa4-11e7-82ba-a6b49b9a8802.png">

Here are some more texture explorations for the hero banner:
![green slash](https://cloud.githubusercontent.com/assets/2492510/26367129/68c09404-3fa2-11e7-88e2-b357d3cde7ed.png)
![green mosaic](https://cloud.githubusercontent.com/assets/2492510/26367127/68bb7370-3fa2-11e7-867c-84f5ddf067c8.png)
![cyan angle diamond waves](https://cloud.githubusercontent.com/assets/2492510/26367126/68ba0738-3fa2-11e7-9a07-bbd694350815.png)
![gradient triangles](https://cloud.githubusercontent.com/assets/2492510/26367128/68bf30aa-3fa2-11e7-8126-a1b78d6dacd6.png)
![gradient wave](https://cloud.githubusercontent.com/assets/2492510/26367125/68b94e60-3fa2-11e7-9146-2fc214767510.png)

So far, I like the gradient triangle exploration and I'll explore some possible line illustrations to accompany it on the right.

cc/ @taisdesouzalessa

**Comment by sabrinang** [comment]
Will be updating a redpen link here: https://redpen.io/p/pgdfcdc63cbd9b0af6

**Comment by taisdesouzalessa** [comment]
I really like the triangle exploration too, @sabrinang. I feel it is a nice visual indicator of the power of the Network and all its connections. Awesome work on all the proposals, they all look very nice!
Also, I am a huge fan of the neutral top nav. It makes the choice of hero images less restrictive.

**Comment by hannahkane** [comment]
Love the symbolism of the triangles!

**Comment by xmatthewx** [comment]
@sabrinang - thanks for sharing the redpens. You showed me several explorations on vidyo in your illustrator doc that I don't see in redpen. Some were strong and potentially more viable. If you can, pull in a few of those, particularly options without a gradient background.

**Comment by sabrinang** [comment]
Thanks for the feedback @xmatthewx. I'll continue iterating on redpen (https://redpen.io/p/pgdfcdc63cbd9b0af6) focusing on feedback you mentioned as well exploring including of people line art (from slide deck presentation) and photography from the discussion with Jesse earlier today.

@jessevondoom - if you have people line art assets or photography that I can use for the hero, feel free to share them here.

**Comment by xmatthewx** [comment]
tracking in a new issue.
