### ISSUE TITLE
Network Site Visual Assets

### ISSUE THREAD

**Issue by sabrinang** [mozilla/network#66]
The Mozilla Network site needs some visuals like icon, illustrations or photos etc. that are not content dependent:

**Home Page**
- [ ] hero graphic (#60)
- [x] join us graphic (#45)
- [x] people collage graphic 
- [x] project collage graphic

**About Us Page**
- [x] header graphic (#35)
- [x] we'd love to hear from you graphic (#28)

**Programs Page** (#30)
- [x] Event photo
- [x] Training photo
- [x] Fellowship photo
- [x] Grants photo
- [x] Local organizing photo
- [x] Research photo
- [x] Science photo
- [x] Women and web lit photo
- [x] Internet of things photo
- [x] Learning photo

**Thank you Page**
- [x] thank you graphic (#46)

**Comment by xmatthewx** [comment]
adding Upcoming page above 

Also see items listed in https://github.com/mozilla/network/issues/67 to make sure we aren't missing anything..

**Comment by sabrinang** [comment]
I think issue #67 was framed in a way to gather content specific assets that is dependent on content selected which is different than how this is framed as this ticket focuses more on evergreen, not content dependent visual assets.

**Comment by sabrinang** [comment]
cc @natalieworth

**Comment by xmatthewx** [comment]
> issue #67 was framed in a way to gather content specific assets ... this ticket focuses more on evergreen assets

Should we reopen #67? Useful for you?

**Comment by sabrinang** [comment]
@xmatthewx Yeah we should reopen the ticket and update that check list as content is confirmed and will flag staff from that ticket to collect content dependent visual content.

**Comment by sabrinang** [comment]
chatted with @natalieworth to align visuals and brand approach that informs this work: https://public.etherpad-mozilla.org/p/visual-exploration-mofo

**Comment by sabrinang** [comment]
Gathered 10 images for programs page as well as some for backup options:
![preview-photo_contact-sheet](https://cloud.githubusercontent.com/assets/2492510/23237632/176e4130-f913-11e6-89c8-c3a8ef9cb6b7.png)

Collected from our flickrs and stock photography and work in progress now to adjusting tone/contrast and how they appear on mobile.

**Comment by sabrinang** [comment]
@xmatthewx Photo review? or any feedback on the mood/brand alignment?
 
![programs](https://cloud.githubusercontent.com/assets/2492510/23283320/1ac93746-f9da-11e6-89e0-f021e68fe570.jpg)

Photography Sources:
- https://www.flickr.com/photos/newyouthcity/albums/72157666155033344
- https://www.flickr.com/photos/newyouthcity/albums/72157634424890339
- https://www.flickr.com/photos/laura_nk/albums/72157649063963096
- https://drive.google.com/drive/u/1/folders/0ByEwfEUJ9QP0dlVhV0l3eklTUlk
- https://unsplash.com/

**Comment by xmatthewx** [comment]
Looks good to me. The fellowships one is a wee bit cheesy, but it's also a good break from the people/event shots. 👍

**Comment by xmatthewx** [comment]
On the stuff above, is the photo of people in jeans a placeholder? beyond that, things look good. I would avoid too many photos of elementary school kids unless they are targeted to a kid specific thing. 👍

**Comment by sabrinang** [comment]
@xmatthewx I'm not sure which photo you are referencing with people wearing jeans but no placeholders (I'll leave placeholders as blue boxes) - I can find an alternative to which ever photo you want to swap out

**Comment by xmatthewx** [comment]
Hi. Sorry if my comment seemed hasty. "Open Web fellows announced" is the jeans photo here on Upcoming: https://github.com/mozilla/network/issues/67#issuecomment-282354794

See my comment at the bottom of this thread for more info.

**Comment by sabrinang** [comment]
<img width="1257" alt="screen shot" src="https://cloud.githubusercontent.com/assets/2492510/23914704/f924bc5e-08a3-11e7-9ea2-65c555f8b3fa.png">

![network-icons-in-context](https://cloud.githubusercontent.com/assets/2492510/23914698/f42055ba-08a3-11e7-8cf0-7fec6f15e16d.png)

exports in gdrive folder: https://drive.google.com/drive/folders/0B4Q8pzCpDS_eazZIWWJ5cWg1Njg?usp=sharing

**Comment by sabrinang** [comment]
line art updated to 1 color: https://drive.google.com/drive/folders/0B4Q8pzCpDS_eazZIWWJ5cWg1Njg?usp=sharing
<img width="1014" alt="screen shot 2017-03-14 at 12 14 36 pm" src="https://cloud.githubusercontent.com/assets/2492510/23918352/e28ce122-08af-11e7-8c4c-8ff3acef61b5.png">

![network-icons-in-context-green](https://cloud.githubusercontent.com/assets/2492510/23918354/e38436e8-08af-11e7-91d8-9cd48f872d54.png)

**Comment by sabrinang** [comment]
![image-in-context](https://cloud.githubusercontent.com/assets/2492510/23929469/a1469b70-08e3-11e7-84a7-25efc8bf9b5b.jpg)

People and project collages exported here: https://drive.google.com/drive/folders/0B4Q8pzCpDS_edXF6SFNBNUg3bDQ?usp=sharing
