### ISSUE TITLE
Rebalance Homepage

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#786]
We want to adjust hierarchy on the homepage. Jesse's [doc with notes and wireframe](https://docs.google.com/document/d/1KHupYYJIUO3woYa3CpmZwib_xgYHg9yN13KmtqSTuRQ/edit#)

Tickets to file:
 - [x] #794 Remove the member preview banner.
 - [x] #791 [Design] Condense the hero in general, as well as the “Become a champion…” header
 - [x] #792 [Design] Added a few lines for either a summary or editorial commentary. Not necessary this sprint, but worth exploring?
 - [x] #793 Network leaders move down on page. Move the “Latest from our network” section up to the top, making news and narrative more prominently featured. 
 - [x] Get Involved remains untouched

_Taís' edits_
Implementation tickets below:
- [ ] #821 
- [ ] #793

**Comment by xmatthewx** [comment]
Tickets are filed. I'm going to assign @taisdesouzalessa to keep track of this epic.

**Comment by taisdesouzalessa** [comment]
Blocked by: waiting on feedback to move on. 

Mockups and considerations posted here:
https://github.com/mozilla/network/issues/791#issuecomment-333688967

**Comment by xmatthewx** [comment]
I think the last step on this is news item descriptions. We just need specs on that, unless there's a specific design concern.

**Comment by alanmoo** [comment]
I went a step too far down the rabbit hole, but I think my question still stands: What dev tickets need to be filed at this point for rebalancing?

**Comment by taisdesouzalessa** [comment]
Hey @alanmoo #792 (see Matthew's comment [here](https://github.com/mozilla/network/issues/792#issuecomment-334517112)) and #793. I can file the implementation tickets if you want. 
@xmatthewx anything I am missing?

**Comment by alanmoo** [comment]
What about moving things around?

**Comment by taisdesouzalessa** [comment]
@alanmoo implementation ticket filed here: #821. Matthew had filed this one: #793. 

Not sure what I should do with this epic...close?

**Comment by xmatthewx** [comment]
No new tickets required. When News descriptions land, we can close this epic.

**Comment by xmatthewx** [comment]
5 of 5 issues completed and reviewed. closing!
