### ISSUE TITLE
Pages status - DESKTOP

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#95]
This ticket provides an overview of all the pages we are building and the design status of each one.

**Home Page** 
[Preview](https://invis.io/ZJ9YTAGEA#/216715355_Home-Page-Opt1)
Design Tickets (on iterations after staff feedback): #92 (p2) #91 (p1) - now merged #104
- [x] First pass on design
- [x] Iterations after staff's feedback ----> _IN PROGRESS_
- [x] Ready for development 
------
**People** 
[Preview](https://invis.io/ZJ9YTAGEA#/221081570_People-Front-Card)
Design Ticket: #39 --- Keep in mind mobile tag issue:  #58
Implement Ticket: #33 
- [x] First pass on design
- [x] Iterations after staff's feedback ----> _no feedback here_
- [x] Ready for development 
- [ ] Visual Assets (collecting headshots, partner logos #67 
------
**Programs** 
[Preview](https://invis.io/ZJ9YTAGEA#/216715364_Programs)
Design Ticket:  #30
- [x] First pass on design
- [x] Ready for development 
- [ ] POST-LAUNCH Iterations after staff's feedback ----> _IN PROGRESS: we may remove Themes section from this page and add elements from "Upcoming"; also consider copy changes from #73_

------
**Projects** 
[Preview](https://invis.io/ZJ9YTAGEA#/217251312_Projects-Join-Us-Iteration)
Design Ticket: #38
- [x] First pass on design
- [x] Ready for development - add button linking to Pulse
- [ ] POST-LAUNCH Iterations after staff's feedback ----> _IN PROGRESS: we may add "buckets" to this page and integrate Campaigns there (see #90)_
------
**Campaigns** 
[Preview](https://invis.io/ZJ9YTAGEA#/216715353_Campaigns)
Design Ticket: #78
- [x] First pass on design
- [x] Ready for development: Remove this page for launch #97
------
**Upcoming** 
[Preview](https://invis.io/ZJ9YTAGEA#/216715367_Upcoming)
Design Ticket: #31
- [x] First pass on design
- [x] Ready for development (we will run with initial comp. redesign for post-launch)
- [ ] POST-LAUNCH Iterations after staff's feedback ----> _IN PROGRESS: we may move this page to "Programs"_
------
**About** 
[Preview](https://invis.io/ZJ9YTAGEA#/216715351_About)
Design Ticket: #35
- [x] First pass on design
- [x] Ready for development 
- [ ] Iterations after staff's feedback ----> _IN PROGRESS: we may have minor changes in this page if we remove "Campaigns" page and if we merge some of the pages as stated above_
------
**Opportunity Landing Page** 
[Preview](https://invis.io/ZJ9YTAGEA#/216715361_Interstitial-Internet-Health)
Design Ticket: #29
- [x] First pass on design
- [x] Iterations after staff's feedback
  - [x] Content for Internet Health page ----> _DONE (mockup in #29)_
  - [x] Content for Trainings page ----> _DONE (copy [here]_(https://github.com/mozilla/network/issues/44#issuecomment-283819302), but no mockup) 
  - [x] Content for Fellowships page ----> _DONE #84_ 
- [x] Ready for development 
-----
**News Page** 
[Preview](https://invis.io/ZJ9YTAGEA#/216715362_News)
Design Ticket:  #36
- [x] First pass on design
- [x] Iterations after staff's feedback
- [x] Ready for development 
----
**Join Us flow**
- [x] First pass on design
- [ ] Iterations after staff's feedback
- [ ] Ready for development 
----
**Nav / Labels**
 - [ ] IA #41 
 - [ ] Ready for dev

**Comment by xmatthewx** [comment]
Let's add "Landing Page" as an item on this list.

**Comment by xmatthewx** [comment]
Let's also add Nav/Page labels to this status list.

**Comment by xmatthewx** [comment]
As we clarify pre-preview-launch, post-preview-launch, we should add copy tasks to our list as well. For some pages, we will aim for copy updates pre- even if we will save full iteration for post-. Programs page for example.

**Comment by hannahkane** [comment]
@xmatthewx - I added Nav as an item, but can you clarify what you mean by adding "Landing page" as an item?

**Comment by xmatthewx** [comment]
Disregard. I now see "Opportunity Landing Page" up above.

**Comment by hannahkane** [comment]
I think this issue has served it's purpose. Closing!
